modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="autokit"
version="1.0.0"
displayName="AutoKit"
credits="The_WereF0X"
displayURL="https://discord.gg/VmvQjHkyVZ"
updateJSONURL="https://discord.gg/VmvQjHkyVZ"
authors="The_WereF0X"
description="Autokits a player when they join the server."

[[dependencies.autokit]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




